
-   id: gen-requirements
    name: gen-requirements
    description: 'gen-requirements: Generates requirements file'
    entry: 'requirements'
    language: python
    files: (Pipfile|poetry)\.lock$
