
-   id: gen-requirements
    name: gen-requirements
    description: 'gen-requirements: Generates requirements file'
    entry: './gen-requirements.sh'
    language: script
    files: 
        - Pipfile.lock
        - poetry.lock